<?php /*
    Copyright (C) Nathanael Schaeffer

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/ ?>
<div class="ftr">
	<div>
		<a target="autres" href="http://natnco.free.fr"><img src="gfx/Natnco_LogoV1_xs.png" style="border-style: none; width: 80%;"></a>
	</div>
	<div style="text-align: center; font-size: 70%">
		<u>Sites index&eacute;s :</u> <a href="http://www.bivouak.net/">bivouak.net</a>, 
			<a target="autres" href="http://www.camptocamp.org/">camptocamp.org (c2c)</a>,
			<a target="autres" href="http://www.gulliver.it/">gulliver.it</a>, 
			<a target="autres" href="http://www.skitour.fr/">Skitour</a>,
			<a target="autres" href="http://www.volopress.net/">Volopress</a>.
			<a target="autres" href="https://www.gipfelbuch.ch">Gipfelbuch.ch</a>.
		<br>
		<i>D'autres sites devraient &ecirc;tre index&eacute;s ? Remarques ? suggestions ? faites-le savoir sur le <a href="https://forum.camptocamp.org/" target="c2c">Forum camptocamp.org</a></i>
	</div>
	<div>
		<img src="gfx/ski_small.png" style="border-style: none; width: 100%;">
	</div>
</div>


